# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a05c23ae04d381866e2c09e8a1ea991e5549a8684e7a9a35747be65a7aea7acbe59fe62f1df6312d8854990e70d02ee4f546b3f25fa2c0f66b730173a14eb1e8

test:
  secret_key_base: 1a50ac0896d0019ce4dd894bd4996d267f0a15f3fb86a5b5aeb01745eae6e1cc9f2cf41fd4652451344741253817dbc70537bfccaf61fd12d21319360f9c6ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
